RUN userdel -r -f alarm

COPY stages/ssh-root/pubkeys pubkeys
RUN mkdir -v -p /root/.ssh \
	&& chmod --verbose 700 /root/.ssh \
	&& cat pubkeys/*.pub >> /root/.ssh/authorized_keys \
	&& chmod --verbose 600 /root/.ssh/authorized_keys \
	&& rm -rfv pubkeys

RUN passwd -l root \
	&& echo "PasswordAuthentication no" >> "/etc/ssh/sshd_config"
