#!/bin/sh
if [ `whoami` != root ]; then
	echo "Only root can do that"
	exit 1
fi
pacman --noconfirm --ask=4 -Syu --verbose && pacman --noconfirm --ask=4 --needed -S --verbose $@
retval=$?
rm -rfv /var/cache/pacman/pkg/*
exit $retval
